name: CI

on:
  workflow_dispatch:

jobs:
  import-data:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
  
      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyverse 
            any::zoo
  
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Save a file
        run: Rscript -e 'x<-runif(10);save(x,file="tmp.RData")'
        
      - name: Upload RData file
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: tmp.RData
