name: CI

on:
  workflow_dispatch:

jobs:
  import-data:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
  
      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyverse 
            any::zoo
  
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Save a file
        run: Rscript -e 'file.create("my.csv")'
        
      - name: Commit RData file
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add my.csv
          git commit -m "Add my.csv"
          git push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
